import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, NgZone, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { BehaviorSubject } from 'rxjs';
import * as i0 from "@angular/core";
export declare class SiiPageContainerComponent implements AfterViewInit, OnChanges, OnDestroy {
    private el;
    private ref;
    sanitizer: DomSanitizer;
    private zone;
    clickOutsideDetail: EventEmitter<any>;
    toggleFilterPanel: EventEmitter<any>;
    autoHiddenToolbar: boolean;
    scrollerRef: HTMLInputElement | any;
    backgroundImgUrl: string;
    hideBackgroundImg: boolean;
    backgroundClass: any;
    get toolbarHeight(): string;
    get pageContentToolbarsContainerHeightVal(): string;
    get fixedToolbarHeight(): string;
    get footerHeight(): string;
    get headeHeight(): string;
    lastToolbarVisibilityChangeTime: number;
    realScrollerRef: any;
    private filterHoverMask;
    private detailHoverMask;
    private pageFiltersComponent;
    private pageDetailComponent;
    private pageContentComponent;
    private pageContentToolbarComponent;
    private toolbarComponent;
    private footerComponent;
    ptContainer: ElementRef;
    pctContainer: ElementRef;
    footerContainer: ElementRef;
    headerContainer: ElementRef;
    miniHeaderContainer: ElementRef;
    hiddenSiiToolbar: boolean;
    siiPageScrolled: boolean;
    initialized: boolean;
    pageToolbarContainerHeightSubj: BehaviorSubject<number>;
    pageToolbarContainerHeight: import("rxjs").Observable<number>;
    pageFixedToolbarContainerHeightSubj: BehaviorSubject<number>;
    pageFixedToolbarContainerHeight: import("rxjs").Observable<number>;
    pageContentToolbarsContainerHeightSubj: BehaviorSubject<number>;
    pageContentToolbarsContainerHeight: import("rxjs").Observable<number>;
    pageFixedContentToolbarsContainerHeightSubj: BehaviorSubject<number>;
    pageFixedContentToolbarsContainerHeight: import("rxjs").Observable<number>;
    pageFooterContainerHeightSubj: BehaviorSubject<number>;
    pageFooterContainerHeight: import("rxjs").Observable<number>;
    pageHeaderContainerHeightSubj: BehaviorSubject<number>;
    pageHeaderContainerHeight: import("rxjs").Observable<number>;
    pageMiniHeaderContainerHeightSubj: BehaviorSubject<number>;
    pageMiniHeaderContainerHeight: import("rxjs").Observable<number>;
    pageFooterContainerVisibleHeightSubj: BehaviorSubject<number>;
    pageFooterContainerVisibleHeight: import("rxjs").Observable<number>;
    pageHeaderContainerVisibleHeightSubj: BehaviorSubject<number>;
    pageHeaderContainerVisibleHeight: import("rxjs").Observable<number>;
    showMiniHeader: boolean;
    pageToolbarContainerObserver: any;
    pageContentToolbarsContainerObserver: any;
    pageFooterContainerObserver: any;
    pageHeaderContainerObserver: any;
    pageMiniHeaderContainerObserver: any;
    scrollerContainerObserver: any;
    addFooterSpace: boolean;
    id: number;
    lastScrollTop: number;
    utils: {
        lastpctbItems: number;
    };
    scrollFunctionRef: any;
    onResize(event: any): void;
    constructor(el: ElementRef, ref: ChangeDetectorRef, sanitizer: DomSanitizer, zone: NgZone);
    ngOnChanges(changes: SimpleChanges): void;
    updateBgImage(): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    checkFooterVisibility(srcElement: any): void;
    checkHeaderVisibility(srcElement: any): void;
    private positiveOrZero;
    showHideToolbar(srcElement: any): void;
    emitToolbarHideEvent(): void;
    initScroller(): void;
    subscribeScrollInterceptor(): void;
    toggleFiltersPanel(forceStatusVisible?: boolean): void;
    toggleDetailPanel(forceStatusVisible?: boolean): void;
    private fixLayout;
    private showDetailPanel;
    private hideDetailPanel;
    private showHideDetailHoverMask;
    private showFiltersPanel;
    private showHideFiltersHoverMask;
    private hideFiltersPanel;
    getRealWidth(): number;
    detailHoverMaskClick(): void;
    filterHoverMaskClick(): void;
    toolbarsHeightChange(): void;
    disableContentScroll(enable: boolean): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SiiPageContainerComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SiiPageContainerComponent, "sii-page-container", never, { "autoHiddenToolbar": { "alias": "autoHiddenToolbar"; "required": false; }; "scrollerRef": { "alias": "scrollerRef"; "required": false; }; "backgroundImgUrl": { "alias": "backgroundImgUrl"; "required": false; }; "hideBackgroundImg": { "alias": "hideBackgroundImg"; "required": false; }; "backgroundClass": { "alias": "backgroundClass"; "required": false; }; }, { "clickOutsideDetail": "clickOutsideDetail"; "toggleFilterPanel": "toggleFilterPanel"; }, ["pageFiltersComponent", "pageDetailComponent", "pageContentComponent", "toolbarComponent", "footerComponent", "pageContentToolbarComponent"], ["sii-toolbar", "sii-page-content-toolbar", "[siiPageMiniHeader]", "[siiPageHeader]", "sii-page-filters", "sii-page-content", "sii-page-detail", "[siiPageFooter]"], true, never>;
}
