import { AfterViewInit, SimpleChanges, OnChanges, OnDestroy } from '@angular/core';
import { SiiFacetOptionDto } from '../dto/i-sii-facet-option.dto';
import { FacetSkeletonComponent } from '../facet-skeleton/facet-skeleton.component';
import { SiiFacetService } from '../service/sii-facet.service';
import { SiiFacetDto } from '../dto/i-sii-facet.dto';
import * as i0 from "@angular/core";
export declare abstract class PrimitiveFacetDirective implements OnDestroy, AfterViewInit, OnChanges {
    siiFacetService: SiiFacetService;
    config: SiiFacetDto;
    expanded: boolean;
    label: string;
    initMultiplicityToDisplay: number;
    visibleFacetsSize: number;
    hideSelection: boolean;
    set multiplicityToDisplay(val: number);
    get multiplicityToDisplay(): number;
    set facetExpanded(val: boolean);
    get facetExpanded(): boolean;
    private readonly subscriptions;
    skelRef: FacetSkeletonComponent;
    _optionsInitValue: any;
    set optionsInitValue(val: any);
    get optionsInitValue(): any;
    get facetSelection(): any;
    set facetSelection(val: any);
    get selectedFacets(): any;
    constructor(siiFacetService: SiiFacetService);
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInitCallback(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    removeFacetSelectionFromFacetSummaryCallback(fs: SiiFacetDto): void;
    getInitSelection(): any;
    private extractFacetFromList;
    addSelection(item: SiiFacetOptionDto): void;
    removeSelection(item: SiiFacetOptionDto, propagate?: boolean): void;
    removeAllSelections(): void;
    changeFacets(facets: Array<string>): void;
    toggle(opt: SiiFacetOptionDto): void;
    updateFacetSelection(propagateChange?: boolean): void;
    instanceOfSiiFacetOptionDto(object: any): object is SiiFacetOptionDto;
    static ɵfac: i0.ɵɵFactoryDeclaration<PrimitiveFacetDirective, never>;
    static ɵdir: i0.ɵɵDirectiveDeclaration<PrimitiveFacetDirective, never, never, { "config": { "alias": "config"; "required": false; }; "expanded": { "alias": "expanded"; "required": false; }; "label": { "alias": "label"; "required": false; }; "initMultiplicityToDisplay": { "alias": "initMultiplicityToDisplay"; "required": false; }; "visibleFacetsSize": { "alias": "visibleFacetsSize"; "required": false; }; "hideSelection": { "alias": "hideSelection"; "required": false; }; }, {}, never, never, false, never>;
}
