import { BehaviorSubject } from 'rxjs';
import { SiiListController } from '../../../../service/sii-list-controller.service';
import { ISiiPageResponseDTO } from '../../../../dto/i-sii-page-response.dto';
import { ChangeDetectorRef } from '@angular/core';
import { SorterGroupAction } from '../../../../components/list-sorter/list-sorter-option/list-sorter-option.component';
export type CisGroup = {
    items: any;
    label: string;
    key: string;
    firstItem: number;
    lastItem: number;
    length: number;
    parentGroupKey?: any;
    parentGroupValue?: any;
    isFirstOfparentGroup?: boolean;
    parentGroupLabelTransform?: (rid: any, value: any, obj: any) => string;
    groupLabelTransform?: (rid: any, value: any, obj: any) => string;
    groupAction?: SorterGroupAction[];
    parentGroupAction?: SorterGroupAction[];
};
export declare class SiiGroupedInfiniteScrollDataSource {
    siiListController: SiiListController;
    private ref;
    get data(): BehaviorSubject<object[]>;
    get dataValue(): object[];
    get fetchSize(): number;
    get listSize(): number;
    get displayedListSize(): number;
    get visibleGroups(): {};
    get bySiiId(): {};
    private utils;
    private lastFetchedpage;
    private _cachedData;
    private _displayedData;
    private _dataStream;
    private _subscription;
    constructor(siiListController: SiiListController, ref: ChangeDetectorRef);
    fetchNextPage(): void;
    get haveCollapsedGroups(): boolean;
    isGroupCollapsed(key: any): boolean;
    isParentGroupCollapsed(key: any): boolean;
    parentGroupSize(key: any): number;
    private _fetchPage;
    listChangeSubscriptionFunction: (page: number, res: ISiiPageResponseDTO<any>, reset: boolean) => void;
    fillCachedData: (toIndex: number) => void;
    buildData(): void;
    addGroupPointer(pos: number, item: any): void;
    getGroupKey(record: any): any;
    buildGroups(): void;
    toggleparentGroup(parentGroupId: any): void;
    toggleGroup(group: CisGroup): void;
    fetchItemsAfterCollapse(): void;
    refreshSubscriptionFunction(): void;
    selectAllSubscriptionFunction(): void;
    checkForSelectAll(page: any): void;
}
