import { SiiFacetedPageRequestDTO } from '../dto/i-sii-faceted-page-request.dto';
import { ISiiPageResponseDTO } from '../dto/i-sii-page-response.dto';
import { Observable, Subject, BehaviorSubject, Subscription } from 'rxjs';
import { SiiFacetedPageResponseDTO } from '../components/facets/common/dto/i-sii-faceted-page-response.dto';
import { SiiFacetDto } from '../components/facets/common/dto/i-sii-facet.dto';
import { SiiSortDTO } from '../dto/i-sii-sort.dto';
import { FacetChangesDto } from '../components/facets/common/service/sii-facet.service';
import { SiiWaitService } from '../components/wait/sii-wait.service';
import { SiiSortGroup } from '../dto/i-sii-group.dto';
import * as i0 from "@angular/core";
export type SiiListRestServiceType = (request: SiiFacetedPageRequestDTO) => Observable<SiiFacetedPageResponseDTO<any>>;
export type selectionStatusType = 'A' | 'P' | 'N';
export declare class SiiListController {
    private waitService;
    private _fetchService;
    private _autosaveId;
    private _skipInitFacets;
    _fetchSize: number;
    _itemId: any;
    _currentpage: number;
    _lastEvaluatedKeyOfPage: {};
    _maxFetchSize: number;
    _sortField: SiiSortDTO;
    _groupField: SiiSortGroup;
    selectAllInProgress: boolean;
    currentFetchCall: Subscription[];
    private _lastFetchRequestInfo;
    set lastFetchRequestInfo(lfri: ISiiPageResponseDTO<any>);
    get lastFetchRequestInfo(): ISiiPageResponseDTO<any>;
    lastFacetRequest: FacetChangesDto;
    _selectionStatus: selectionStatusType;
    _selectionMap: {};
    private _facetChangeSubj;
    facetsData: Observable<SiiFacetDto[]>;
    doFetchPage: Subject<number>;
    private fetchPage;
    executeSearch: Subject<boolean>;
    private executeSearchObs;
    facetsChange: Subject<FacetChangesDto>;
    private facetsChangeObs;
    facetsReset: Subject<object>;
    private facetsResetObs;
    sortChange: Subject<void>;
    private sortChangeObs;
    private _fetchPageDataSubj;
    fetchPageData: Observable<{
        page: number;
        rows: ISiiPageResponseDTO<any>;
        reset: boolean;
    }>;
    private _selectedItemChangeSubj;
    private _selectedItemsChangeSubj;
    private _selectAllSubj;
    selectAllObs: Observable<void>;
    private _refreshSubj;
    refreshObs: Observable<void>;
    private setInitFacetsSubj;
    setInitFacetsObs: Observable<FacetChangesDto>;
    private changeFacetsSubj;
    changeFacetsObs: Observable<{
        facets: object;
        reset: boolean;
    }>;
    private changeSearchTextSubj;
    changeSearchTextObs: Observable<string>;
    private semaphoreFetch;
    fetchInProgress: BehaviorSubject<boolean>;
    fetchInProgressObs: Observable<boolean>;
    api: {
        setAutoSave: (id: string, skipInitFacets?: boolean) => void;
        setFetchService: (restService: SiiListRestServiceType) => SiiListRestServiceType;
        setFetchSize: (fs: number) => number;
        setItemId: (id: string) => string;
        setMaxFetchSize: (mfs: number) => number;
        setInitFacets: (initFacets: object, searchText?: string) => void;
        changeFacets: (facets?: object, searchText?: string, resetOthers?: boolean) => void;
        selectedItemChange: Observable<object>;
        selectedItemsChange: Observable<object[]>;
        selectAll: () => void;
        deselectAll: () => void;
        refresh: () => void;
        reset: () => void;
        getFacet: (facetRef: any) => any;
        itemsCount: number;
        selectedItemsCount: number;
        getSelectedItems: () => any[];
        getFetchRequestData: () => SiiFacetedPageRequestDTO;
    };
    constructor(waitService: SiiWaitService);
    private setAutosave;
    private setInitfacets;
    private changeFacets;
    private getFetchRequestData;
    private executeSearchFunction;
    hideFetchSpinner(): void;
    showFetchSpinner(): void;
    multiselectItemClick(selecteditem: any): void;
    markAsSelected(items: any[]): void;
    removeMissingSelection(items: any[]): void;
    singleselectItemClick(selecteditem: any): void;
    private updateSelectionStatus;
    isSelected: (item: any) => boolean;
    get selectionStatus(): selectionStatusType;
    selectAll(): void;
    deselectAll(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SiiListController, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<SiiListController>;
}
