import { OnInit, OnDestroy, ElementRef, AfterViewInit, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { MyselfDTO } from '../../dto/myself.dto';
import { HelpPageDTO } from '../../dto/help-page.dto';
import { BehaviorSubject } from 'rxjs';
import { SiiToolkitService } from '../../sii-toolkit.service';
import { SiiMenuVoice } from '../menu/global-menu/dto/menu-voice';
import { SiiEngageService } from '../../service/sii-engage.service';
import { Router } from '@angular/router';
import { ToolbarMenuCategory, ToolbarMenuDto, ToolbarSubmenuItemOpenIn } from '../../dto/toolbar-menu.dto';
import { SiiMenuFolder } from '../menu/global-menu/dto/menu-folder';
import { SdacPreviewService } from '../dsii-components/sdac-preview/service/sdac-preview.service';
import { BreakpointObserver } from '@angular/cdk/layout';
import { SiiBreadcrumbService } from '../breadcrumb/services/breadcrumb.service';
import { DelegationService } from '../dsii-components/delegation/delegation.service';
import { SiiDownloadService } from '../../service/sii-download-service';
import * as i0 from "@angular/core";
export declare class ToolbarComponent implements OnInit, OnDestroy, AfterViewInit, OnChanges {
    private siiToolkitService;
    el: ElementRef;
    private engageServ;
    private sdacPreviewService;
    router: Router;
    breakpointObserver: BreakpointObserver;
    private siiBreadcrumbServ;
    delegationService: DelegationService;
    siiDownloadService: SiiDownloadService;
    autoHide: boolean;
    toolbarTitle: string;
    menu: SiiMenuVoice[];
    applicationMenu: ToolbarMenuCategory[];
    helpId: string;
    showEngageSearch: boolean;
    showEngageMenu: boolean;
    showCloseButton: boolean;
    closeAction: EventEmitter<void>;
    helPage: HelpPageDTO;
    menuVoices: BehaviorSubject<ToolbarMenuDto>;
    menuMobileOpen: boolean;
    subMenuOpenStatus: any;
    mobileToolbar: boolean;
    activeMobMenu: string;
    menuSidebarVisible: boolean;
    toggleMenuSidebar(forceStatus?: boolean): void;
    get mySelf(): MyselfDTO;
    get haveNotification(): boolean;
    get sdacNotification(): BehaviorSubject<any[]>;
    get sdacTichet(): BehaviorSubject<any[]>;
    get sdacTicketCount(): number;
    get sdacNotificationCount(): number;
    get corporateItCalendarEvents(): BehaviorSubject<import("../../dto/OfficeCalendarEvents.dto").OfficeEvent[]>;
    get corporateItCalendarEventsCount(): number;
    get isServerless(): boolean;
    get isEngage(): boolean;
    get isEngageAvailable(): boolean;
    get engMenuOk(): boolean;
    get appMenuOk(): boolean;
    get appMenuActive(): boolean;
    private readonly subscriptions;
    get boxShadow(): string;
    constructor(siiToolkitService: SiiToolkitService, el: ElementRef, engageServ: SiiEngageService, sdacPreviewService: SdacPreviewService, router: Router, breakpointObserver: BreakpointObserver, siiBreadcrumbServ: SiiBreadcrumbService, delegationService: DelegationService, siiDownloadService: SiiDownloadService);
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
    goToHelpPage(): void;
    closeAct(): void;
    openUrlInWindow(url: string, openIn?: ToolbarSubmenuItemOpenIn): void;
    navigateUrl(voice: any, engageVoice?: boolean): void;
    performSearch(txtSearch?: string): void;
    checkProfiledVoices(voices: SiiMenuFolder[]): void;
    goToHome(): void;
    mobileMenuClick(): void;
    toggleSubmenu(event: any, smIndex: number | string): void;
    doLogout(): void;
    doDelegation(): void;
    doDelegationLogout(): void;
    openSdacTiketsByCode(code?: any): void;
    openSdacNotification(): void;
    openSdacTicket(): void;
    goToDeadlines(): void;
    goToProfile(): void;
    toggleProfileInfo(event: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ToolbarComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ToolbarComponent, "sii-toolbar", never, { "autoHide": { "alias": "autoHide"; "required": false; }; "toolbarTitle": { "alias": "toolbarTitle"; "required": false; }; "menu": { "alias": "menu"; "required": false; }; "applicationMenu": { "alias": "applicationMenu"; "required": false; }; "helpId": { "alias": "helpId"; "required": false; }; "showEngageSearch": { "alias": "showEngageSearch"; "required": false; }; "showEngageMenu": { "alias": "showEngageMenu"; "required": false; }; "showCloseButton": { "alias": "showCloseButton"; "required": false; }; }, { "closeAction": "closeAction"; }, never, ["*"], true, never>;
}
