import { Platform } from '@angular/cdk/platform';
import { ElementRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { DomSanitizer } from '@angular/platform-browser';
import { Observable } from 'rxjs';
import { SiiToolkitService } from '../../sii-toolkit.service';
import * as i0 from "@angular/core";
export declare class UploadComponent implements ControlValueAccessor {
    dialog: MatDialog;
    platform: Platform;
    private sanitizer;
    private ts;
    webcamAvailable: boolean;
    get acceptArray(): string[];
    get acceptText(): string;
    constructor(dialog: MatDialog, platform: Platform, sanitizer: DomSanitizer, ts: SiiToolkitService);
    _multiple: boolean;
    get multiple(): boolean;
    set multiple(value: boolean);
    private isMaxSizeDefault;
    private isMaxSizeSingleDefault;
    _maxSize: number;
    _maxSizeSingleFile: number;
    get maxSize(): number;
    set maxSize(value: number);
    get maxSizeSingleFile(): number;
    set maxSizeSingleFile(value: number);
    accept: string;
    enableCamera: boolean;
    disableDelete: boolean;
    disableCrop: boolean;
    aspectRatio: any;
    resizeToWidth: any;
    downloadService: (id: any) => void | Observable<File>;
    previewService: (id: any) => Observable<File>;
    deleteService: (file: UploadContainerFile) => Observable<boolean>;
    uploadErrorMessage: boolean;
    invalidExt: boolean;
    invalidSize: boolean;
    invalidSizeSingleFile: boolean;
    invalidLength: boolean;
    inputEle: ElementRef;
    fileOver: boolean;
    disabled: boolean;
    selectedFiles: UploadContainerFile[];
    onDragOver(evt: any): void;
    onDragLeave(evt: any): void;
    ondrop(evt: any): void;
    propagateChange: any;
    onTouchedCallback: any;
    validatorCallback: any;
    registerOnValidatorChange?(fn: () => void): void;
    writeValue(obj: UploadContainerFile[] | UploadContainerFile): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState?(isDisabled: boolean): void;
    onFileDropped($event: any): void;
    fileBrowseHandler(files: any): void;
    deleteFile(index: number, file: UploadContainerFile): void;
    loadFilePreviewInformation(fu: UploadContainerFile, force?: boolean): Promise<void>;
    downloadableFile(fu: UploadContainerFile): boolean;
    previewableFile(fu: UploadContainerFile): boolean;
    cropableFile(fu: UploadContainerFile): boolean;
    cropFile(fu: UploadContainerFile, index: any): void;
    previewServiceResponseToFile(resp: any, fu: UploadContainerFile): File;
    previewFile(fu: UploadContainerFile): void;
    downloadFile(fu: UploadContainerFile): void;
    buildDownloadLink(fu: UploadContainerFile): void;
    prepareFilesList(files: Array<any>): void;
    change(files: any): void;
    getFileType(file: File | SiiFile): string | null;
    checkImageToCrop(files: Array<any>): Promise<any[]>;
    performCropFile(index: any): void;
    openCropDialog(file: File): Observable<any>;
    private openPreviewDialog;
    checkFile(files: Array<any>): Promise<unknown>;
    isValidFormat(f: File, acceptArray: Array<string>): boolean;
    isValidSize(f: File): boolean;
    pictImage(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<UploadComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<UploadComponent, "sii-upload", never, { "multiple": { "alias": "multiple"; "required": false; }; "maxSize": { "alias": "maxSize"; "required": false; }; "maxSizeSingleFile": { "alias": "maxSizeSingleFile"; "required": false; }; "accept": { "alias": "accept"; "required": false; }; "enableCamera": { "alias": "enableCamera"; "required": false; }; "disableDelete": { "alias": "disableDelete"; "required": false; }; "disableCrop": { "alias": "disableCrop"; "required": false; }; "aspectRatio": { "alias": "aspectRatio"; "required": false; }; "resizeToWidth": { "alias": "resizeToWidth"; "required": false; }; "downloadService": { "alias": "downloadService"; "required": false; }; "previewService": { "alias": "previewService"; "required": false; }; "deleteService": { "alias": "deleteService"; "required": false; }; }, {}, never, ["[sii-upload-title]", "[sii-upload-description]"], true, never>;
}
export interface UploadContainerFile {
    id: number;
    creationUser?: {
        firstname: string;
        lastname: string;
        userid: string;
    };
    file: File | SiiFile;
    readonly?: boolean;
    prevId?: number;
    _imagePreviewUrl?: any;
    _isImage?: any;
    _type?: string;
}
export interface SiiFile {
    name: string;
    lastModified: number;
    type: string;
    size: number;
}
