import { HttpClient } from '@angular/common/http';
import { OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { AbstractControl, ControlValueAccessor, UntypedFormControl, Validator } from '@angular/forms';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { MatDialog } from '@angular/material/dialog';
import { Observable, Subject } from 'rxjs';
import { ILookupCdcDataDTO } from './domain/lookup-cdc-data.dto';
import { ILookupWorkOrderDataDTO } from './domain/lookup-work-order-data.dto';
import { ILookupWorkOrderDTO } from './domain/lookup-work-order.dto';
import { ILookupIOCdcDataBaseDTO } from './domain/lookup-io-cdc-data.dto';
import { ILookupSubSystemDataDTO } from './domain/lookup-sub-system-data.dto';
import { IPageableLookupCdcDataDTO } from './domain/pageable-lookup-cdc-data.dto.';
import { IPageableLookupWorkOrderDataDTO } from './domain/pageable-lookup-work-order-data.dto';
import { SiiToolkitService } from '../../../sii-toolkit.service';
import { MatFormFieldAppearance } from '@angular/material/form-field';
import * as i0 from "@angular/core";
export declare class LookupWorkOrderComponent implements OnInit, ControlValueAccessor, Validator, OnChanges {
    http: HttpClient;
    dialog: MatDialog;
    siiToolkitService: SiiToolkitService;
    label: string;
    hideCdc: boolean;
    hideIO: boolean;
    hideSS: boolean;
    appearance: MatFormFieldAppearance;
    codSociety: string;
    required: boolean;
    disabled: boolean;
    customIORestFunct: (txt: string) => Observable<ILookupIOCdcDataBaseDTO[]>;
    customCDCRestFunct: (txt: string) => Observable<ILookupIOCdcDataBaseDTO[]>;
    customPageableIORestFunct: (txt: string, page: number, size: number, sortField: string, sortDirection: string) => Observable<IPageableLookupWorkOrderDataDTO>;
    customPageableCDCRestFunct: (txt: string, page: number, size: number, sortField: string, sortDirection: string) => Observable<IPageableLookupCdcDataDTO>;
    refresh: Subject<string>;
    defaultComSS: {
        comSS: string;
        comSSDescription: string;
    };
    lookupInternalOrderComponentCtrl: UntypedFormControl;
    lookupSubSystemComponentCtrl: UntypedFormControl;
    internalOrderRestObs: Observable<ILookupIOCdcDataBaseDTO[]>;
    cdcRestObs: Observable<ILookupIOCdcDataBaseDTO[]>;
    subSystemDataObs: Observable<ILookupSubSystemDataDTO[]>;
    subSystemData: ILookupSubSystemDataDTO[];
    subjectSubSystemDataChange: Subject<string | void>;
    subjectOnChange: Subject<string | void>;
    selectedItem: ILookupWorkOrderDTO;
    utils: {
        subsystemLoadingInProgress: boolean;
        ioLoadingInProgress: boolean;
        cdcLoadingInProgress: boolean;
        internalOrderValid: boolean;
        subSystemValid: boolean;
        forceSearch: number;
    };
    propagateChange: any;
    onTouchedCallback: any;
    validatorCallback: any;
    ngOnInit(): void;
    constructor(http: HttpClient, dialog: MatDialog, siiToolkitService: SiiToolkitService);
    ngOnChanges(changes: SimpleChanges): void;
    getcommCdcInputValueChangeObserver(): Observable<any>;
    displayFn(intOrd?: ILookupWorkOrderDataDTO | ILookupCdcDataDTO): string | undefined;
    displayComSSFn(intOrd?: ILookupSubSystemDataDTO): string | undefined;
    onComSSSelectionChanged(event: MatAutocompleteSelectedEvent): void;
    comSSChange(comSS: ILookupSubSystemDataDTO, updateInputValue?: boolean): void;
    ioCdcChange(item: ILookupIOCdcDataBaseDTO): void;
    onSelectionChanged(event: MatAutocompleteSelectedEvent): void;
    loadSubSystem(): void;
    private checkEnableComSS;
    private _filterSubSystem;
    getIODataFromServer(txt: string): Observable<ILookupIOCdcDataBaseDTO[]>;
    getCDCDataFromServer(txt: string): Observable<any>;
    useIODefaultRestObs(txt: string): Observable<ILookupIOCdcDataBaseDTO[]>;
    useCDCDefaultRestObs(txt: string): Observable<ILookupIOCdcDataBaseDTO[]>;
    searchPopup(): void;
    updateIOComponentValue(): void;
    updateSubSystemComponentValue(): void;
    writeValue(value: ILookupWorkOrderDTO): void;
    onChange(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    registerOnValidatorChange?(fn: () => void): void;
    setDisabledState(isDisabled: boolean): void;
    validate(control: AbstractControl): {
        [key: string]: any;
    } | null;
    static ɵfac: i0.ɵɵFactoryDeclaration<LookupWorkOrderComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<LookupWorkOrderComponent, "sii-lookup-work-order", never, { "label": { "alias": "label"; "required": false; }; "hideCdc": { "alias": "hideCdc"; "required": false; }; "hideIO": { "alias": "hideIO"; "required": false; }; "hideSS": { "alias": "hideSS"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; "codSociety": { "alias": "codSociety"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "customIORestFunct": { "alias": "customIORestFunct"; "required": false; }; "customCDCRestFunct": { "alias": "customCDCRestFunct"; "required": false; }; "customPageableIORestFunct": { "alias": "customPageableIORestFunct"; "required": false; }; "customPageableCDCRestFunct": { "alias": "customPageableCDCRestFunct"; "required": false; }; "refresh": { "alias": "refresh"; "required": false; }; }, {}, never, never, true, never>;
}
