import { ElementRef, OnDestroy } from '@angular/core';
import { SiiFacetService } from '../common/service/sii-facet.service';
import { PrimitiveFacetDirective } from '../common/primitive-facet/primitive-facet.directive';
import { SiiFacetOptionDto } from '../common/dto/i-sii-facet-option.dto';
import { MatSelect } from '@angular/material/select';
import { MatSlideToggle } from '@angular/material/slide-toggle';
import { MatRadioGroup } from '@angular/material/radio';
import { MatInput } from '@angular/material/input';
import { MatDatepickerInput } from '@angular/material/datepicker';
import { LookupEmployeeComponent } from '../../dsii-components/lookup-employee/lookup-employee.component';
import { MatAutocomplete } from '@angular/material/autocomplete';
import { YearMonthInputComponent } from '../../year-month-input/year-month-input.component';
import { SiiDatePipe } from '../../util/sii-date.pipe';
import * as i0 from "@angular/core";
export type FiltersType = 'INPUT' | 'SELECT' | 'TOGGLE' | 'RADIO' | 'DATEPICKER' | 'LOOKUP_EMPLOYEE' | 'AUTOCOMPLETE' | 'YEAR_MONTH';
export declare class SiiFilterDirective extends PrimitiveFacetDirective implements OnDestroy {
    el: ElementRef;
    private siiDatePipe;
    private matInput;
    private matSelect;
    private matSlideToggle;
    private matRadioGroup;
    private matDatepicker;
    private lookupEmployee;
    private matAutocomplete;
    private yearMonthInput;
    set siiFilter(val: string);
    valueTransform: (defaultVal: any) => SiiFacetOptionDto;
    siiFilterInpuRef: HTMLInputElement;
    private privMmultiple;
    get multiple(): boolean;
    set multiple(value: boolean);
    y: any;
    utils: {
        firstValidValueEmitted: boolean;
        initialized: boolean;
    };
    type: FiltersType;
    private valueChangeSubj;
    valueChange: import("rxjs").Observable<any>;
    constructor(el: ElementRef, siiFacetService: SiiFacetService, siiDatePipe: SiiDatePipe, matInput: MatInput, matSelect: MatSelect, matSlideToggle: MatSlideToggle, matRadioGroup: MatRadioGroup, matDatepicker: MatDatepickerInput<any>, lookupEmployee: LookupEmployeeComponent, matAutocomplete: MatAutocomplete, yearMonthInput: YearMonthInputComponent);
    private multiMatSelectValueExtraction;
    ngOnDestroy(): void;
    getOrDefault(value: any, defaultVal?: any): any;
    clearAutocomplete(): void;
    checkType(): void;
    setValue(initSelVal: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SiiFilterDirective, [null, null, null, { optional: true; host: true; }, { optional: true; host: true; }, { optional: true; host: true; }, { optional: true; host: true; }, { optional: true; host: true; }, { optional: true; host: true; }, { optional: true; host: true; }, { optional: true; host: true; }]>;
    static ɵdir: i0.ɵɵDirectiveDeclaration<SiiFilterDirective, "[siiFilter]", never, { "siiFilter": { "alias": "siiFilter"; "required": false; }; "valueTransform": { "alias": "valueTransform"; "required": false; }; "siiFilterInpuRef": { "alias": "siiFilterInpuRef"; "required": false; }; "multiple": { "alias": "multiple"; "required": false; }; }, {}, never, never, true, never>;
}
